Add a Cancel Button when editing a bill
spiral-project/ihatemoney pull request #1013
Opened 2022-04-11 10:52 UTC by erwan-lacoudre

Should close #1001

2022-04-12 10:25 UTC, almet commented
Looks good to me 👍

2022-04-29 17:09 UTC, erwan-lacoudre commented
> I have just seen that the pull request has not pass the tests that seem related to the database. However I have not touch it, maybe there is something I'm missing ?

@almet do you have any idea ? I don't really see what's wrong

2022-04-29 20:19 UTC, almet commented
Hey, it's not related to the work you've done, we have an issue currently on this project which makes the tests not pass. We're currently solving it in #1012. We will merge your changes just after :-)

Thanks, anyways, it seems to be great :-)

2022-05-01 21:04 UTC, Glandos requested changes

2022-05-01 21:04 UTC, Glandos commented on ihatemoney/templates/forms.html
> +            <a href="{{ url_for(".list_bills") }}" class="btn btn-primary"> {{_("Cancel") }} </a>
```suggestion
            <a href="{{ url_for(".list_bills") }}" class="btn btn-outline-secondary"> {{_("Cancel") }} </a>
```

For a better visual UX:
![image](https://user-images.githubusercontent.com/297578/166164584-030fd8c7-15ec-4733-931e-69e3e679215e.png)

2022-05-08 13:37 UTC, Glandos approved these changes

2022-05-08 13:37 UTC, merged

2022-05-08 13:37 UTC, Glandos commented
Thanks!