Fix the problem with total spend on statistic page
spiral-project/ihatemoney pull request #1112
Opened 2022-12-11 23:37 UTC by GingLuo

We're the same team.
Fix the problem with total spend on statistic page
Fix #1019

2023-01-08 14:19 UTC, Glandos requested changes
Thanks for this, it's not that bad for a start!

I left some comment and suggestion.
But to be accepted, we need for unit test. Since the goal of this is to avoid adding refund as expenses, a good test would be to check that refunds are not added to the total expense amount.

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/migrations/versions/2dcb0c0048dc_autologger.py
> +        sa.Column("is_reimbursement", sa.Boolean(), nullable=True),
This file is auto-generated, please read https://ihatemoney.readthedocs.io/en/latest/contributing.html#creating-database-migrations

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/migrations/versions/b9a10d5d63ce_.py
> +        sa.Column("is_reimbursement", sa.Boolean(), nullable=True),
This file is auto-generated, please read https://ihatemoney.readthedocs.io/en/latest/contributing.html#creating-database-migrations

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/models.py
> +                monthly[bill.date.year][bill.date.month] += bill.converted_amount
```suggestion
            if (not bill.is_reimbursement):
                monthly[bill.date.year][bill.date.month] += bill.converted_amount
```

Remove the comment, and don't compare boolean

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/forms.py
> +    is_reimbursement = BooleanField("Reimbursement", default=False)
Add internationalisation call.
```suggestion
    is_reimbursement = BooleanField(_("Reimbursement"), default=False)
```

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/templates/settle_bills.html
> +            </td> -->
Don't commit commented code

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/tests/api_test.py
> +	}
Forget about formatting manually with https://ihatemoney.readthedocs.io/en/latest/contributing.html#formatting-code

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/tests/api_test.py
> +	    "is_reimbursement": false,
Forget about formatting manually with [ihatemoney.readthedocs.io/en/latest/contributing.html#formatting-code](https://ihatemoney.readthedocs.io/en/latest/contributing.html#formatting-code)

2023-01-08 14:19 UTC, Glandos commented on ihatemoney/web.py
> +
I don't see any changes linked to this new route. Was it linked to the commented HTML code?

2023-01-08 14:37 UTC, Glandos commented
By the way, there is another implementation in #1116

2023-01-08 20:28 UTC, GingLuo commented
Hi Glandos,
Really appreciate the suggestions.
I've seen your comments and #1116, so I wonder should we just keep track of the reimbursement as an enum of bill type? 
For me, I feel like Transfer and Reimbursement are kind of the same thing (i.e. from one person to the other person). So to differentiate between Expense and Reimbursement, adding a new boolean column 'is_reimbursement' in the database also works. Or it might be better to keep the bill type as Expense and Reimbursement.
But their PR is more complete than ours, and we are ok to follow their design.
Let me know if you have any questions.
Thanks

2024-04-12 09:38 UTC, zorun commented
Closing because #1290 has been merged

2024-04-12 09:38 UTC, closed without merging