New Click Command
spiral-project/ihatemoney pull request #1114
Opened 2022-12-13 01:22 UTC by adammentzer

Added Click command to display the number of projects. Options exist to specify for projects within the bounds of the specified number of bills (inclusive) and/or less than x days old.

2023-01-28 21:40 UTC, Glandos requested changes
I've added some small Pythonic changes.

But globally, it would better to have a list of predicates to filter the list of project, and execute this list comprehension `project = []` only once.
I bet this is possible with SQLAlchemy, but don't have the time to find it, so, it will be fine for me with Python lambdas :)

2023-01-28 21:40 UTC, Glandos commented on ihatemoney/manage.py
> +            bills_low = temp
```suggestion
        if bills_high < bills_low:
            (bills_low, bill_high) = bills_high, bills_low
```

2023-01-28 21:40 UTC, Glandos commented on ihatemoney/manage.py
> +                and pr.get_bills().count() <= bills_high
```suggestion
                if  bills_low <= pr.get_bills().count() <= bills_high
```

2023-01-28 21:40 UTC, Glandos commented on ihatemoney/manage.py
> +            click.echo(proj_names)
This is duplicated code from line 155-161.

2023-01-28 21:49 UTC, Glandos commented
Also, maybe a default value of 0 for `bills_low` should be a better default, instead of having to chose both low and high.

2024-12-20 17:08 UTC, almet commented
Thanks, this has been done in #1115

2024-12-20 17:08 UTC, closed without merging