Bill Types added to Bill , pay feature added for Settle page, Statistics Page adjusted to be compatible with new types
spiral-project/ihatemoney pull request #1116
Opened 2022-12-13 04:27 UTC by FlowingCloudRTL

# Description
To tackle #137, I took some ideas from the discussion under the issue and made some design changes that are different from the previous PR that was done: 
- Bill Types are added in the Bill model and forms to differentiate refund/reimbursement from expenses of the project. 
   Currently, only three types of bills are hardcoded in as the present for all projects: Expense, Reimbursement, and Transfer. Expense is the normal spending, Reimbursement bill serves to settle the debt within the project, and Transfer is any bills between members that should not be tracked as an expense. 
![image](https://user-images.githubusercontent.com/49292515/207225616-d8e96e3d-45c4-4e87-9dc8-5238d307a5bd.png)
![image](https://user-images.githubusercontent.com/49292515/207225667-3b51a6f8-05e1-4f96-9f55-6928f1753955.png)  
- Settle button is added to directly add a Reimbursement bill to clear out the debt associated with another participant with one click rather than going through another form for better UX. 
![image](https://user-images.githubusercontent.com/49292515/207225717-9501deab-0f2b-4bb7-a16e-60f6dc58d136.png)
- To maintain the Statistics page's functionality, Monthly Expense would only track expense type bills, and when participant A reimburses participant B, A's paid amount would increase and B's paid amount would decrease by the reimbursed amount to maintain the relationship between paid, expense, and balance. (balances = Paid - Spent)
![image](https://user-images.githubusercontent.com/49292515/207226233-31bb4776-0baa-438d-92ae-a477aa9d1ee5.png)

Fixes #137

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✓] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Most tests associated with the Bill model are modified to be compatible with the new bill type attribute. New tests and validations are added for bill type, the pay button on the settle page, and statistics calculations. 
All tests pass except the broken CI/CD in history_test.py 

**Test Configuration**:
* Firmware version: Windows 10
* SDK: Python 3.8.10

# Checklist:

- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [✓] My changes generate no new warnings
- [✓] I have added tests that prove my fix is effective or that my feature works
- [✓] New and existing unit tests pass locally with my changes
- [✓] Any dependent changes have been merged and published in downstream modules

To-Do:
Documentation changes, inline documentation (ideally will be done in the next few days) 
Allow custom types to be added and removed in the project setting
Add more statistics page for different bill types

2023-01-08 14:36 UTC, Glandos requested changes
Thanks for this!
This is a duplicate implementation of #1112, so we have to coordinate this.

I wonder if there is a need for the "Transfer" type.

I also guess that it will be very useful to mark the original bill that created the "Reimbursement". But it's also a lot more work.

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/api/v1/resources.py
> +# )
Don't commit commented code

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/default_settings.py
> +SESSION_COOKIE_SECURE = False
```suggestion
SESSION_COOKIE_SECURE = True
```
Don't modify default settings, especially regarding security.

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/default_settings.py
> +TEMPLATES_AUTO_RELOAD = True
Is this related to this PR?

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/forms.py
> +        _("For Who?"), validators=[DataRequired()], coerce=int
Why change this string?

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/forms.py
> +
I think that you can use a `choices` attribute to the `SelectField` instead of a custom validator.

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/models.py
> +        - dict mapping each member to how much he/she she should pay others
Duplicated "she"

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/models.py
> +        #         )
Remove commented code, it pollutes the diff.

2023-01-08 14:36 UTC, Glandos commented on ihatemoney/models.py
> +    ]
If this is an enum, it's better to use enum typing from SQLAlchemy.

2023-01-08 14:39 UTC, Glandos commented
After seeing your PR, I feel more comfortable with a "Bill type" rather than just a boolean. However, the bill list UI will need a bit more refinement. For example, I feel that we can completely skip the "Bill type" column, and replace it with some icons (with tooltips) on non-expense bills. The rationale: expense bills should be far more common than any others, which then should be "exceptions".

2023-01-31 17:15 UTC, zorun commented
Thanks, I think this goes in the right direction.

As @Glandos said, adding only an icon for each bill (e.g. as a first column) instead of a full "Bill type" column would be better.

I'm not sure about the statistics, it becomes more complex. In your example, looking at total amounts:

- Alice paid 33 in expenses
- Bob paid 45 in expenses
- that's a monthly total expense of 78
- Alice has "spent" 39
- Bob has "spent" 39 (here it's the same as Alice, but it could be different)
- Alice has reimbursed 1 to Bob

I think we should find a way to display all this information in the statistics.

2023-01-31 17:22 UTC, zorun commented
Actually the balance would work if we add a fourth column "reimbursed from":

balance = paid (expenses only) - spent (expenses only) + "reimbursed to others" - "reimbursed from others"

2023-07-17 12:41 UTC, zorun commented
Hi @FlowingCloudRTL , are you still interested in working on this feature?

2023-07-19 03:34 UTC, FlowingCloudRTL commented
Not at the moment

2024-02-25 15:29 UTC, TomRoussel commented
Hi, I've been playing around with this project and I feel like I dedicated "settle up" button is missing for usability. Is there still an interest to tackle it in the way described in this PR? If @FlowingCloudRTL is not interested in working on this feature, I'd like to have a crack at it. I was already able to merge this branch with the current master, and have fixed all unit tests that have been implemented.

Let me know what you think about me taking over this PR.

2024-02-25 15:58 UTC, almet commented
> Let me know what you think about me taking over this PR.

Hey, sure, please go ahead, and let me know when it's ready so I can review :-)

2024-02-25 17:12 UTC, TomRoussel commented
Great! I'll go over the suggested changes above and let you know when it's ready for review.

Purely a practical question: should I make a new PR for this (and link to this one)? Not sure what the typical approach is when picking up a stale PR.

2024-04-12 09:40 UTC, zorun commented
Closing because #1290 has been merged

2024-04-12 09:40 UTC, closed without merging