"a free software" -> "free software"
spiral-project/ihatemoney pull request #818
Opened 2021-07-25 16:58 UTC by georgefst

In English, "software" is an [uncountable noun](https://dictionary.cambridge.org/grammar/british-grammar/uncountable-nouns). You could say "a free piece of software" or "some free software", but in this context it feels most natural to just drop the article entirely.

2021-07-25 20:19 UTC, Glandos requested changes
Thanks for the limpid explanation, and the correction.

However, `.pot` and `.po` files are managed automatically by our Weblate instance, so the must be excluded from the PR itself.

2021-07-25 20:19 UTC, Glandos commented on ihatemoney/templates/layout.html
> +              <a href="https://github.com/spiral-project/ihatemoney">{{ _("\"I hate money\" is free software") }}</a><span class="d-none d-sm-inline"></span>,
Only this part should be left in the PR

2021-07-25 23:51 UTC, georgefst commented
> However, `.pot` and `.po` files are managed automatically by our Weblate instance, so the must be excluded from the PR itself.

Ah okay, I'll have a proper look at that tomorrow. Is it easy to make bulk edits?

2021-07-28 20:35 UTC, Glandos commented
> > However, `.pot` and `.po` files are managed automatically by our Weblate instance, so the must be excluded from the PR itself.
> 
> Ah okay, I'll have a proper look at that tomorrow. Is it easy to make bulk edits?

Yes, no problem. Once the string is edited in the source file, we'll run the string extractor that will re-generate all `.po(t)` files.

2021-08-17 17:54 UTC, georgefst commented
(this should be squash-merged)

2021-08-18 06:54 UTC, merged